function clean(value) {
  return String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ')
}

function xml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')
}

function markdownEvidence(value, evidenceHrefPrefix = null) {
  const cleaned = clean(value)
  return evidenceHrefPrefix !== null && /^evidence\/[A-Za-z0-9._/-]+(?:#[A-Za-z0-9._-]+)?$/.test(cleaned)
    ? `[${cleaned}](${evidenceHrefPrefix}${cleaned})`
    : cleaned
}

const GAP_ORDER = { FAIL: 0, UNPROVEN: 1, PARTIAL: 2 }

export function prioritizedGaps(report) {
  return (report.checks || [])
    .filter(item => Object.hasOwn(GAP_ORDER, item.status))
    .sort((a, b) => GAP_ORDER[a.status] - GAP_ORDER[b.status] || b.points - a.points || a.id.localeCompare(b.id))
}

function appendEvidenceLedger(lines, report, heading = 'Complete evidence ledger', evidenceHrefPrefix = null) {
  lines.push('', `## ${heading}`, '', '| Status | Check | Dimension | Weight | Level | Finding and evidence |', '|---|---|---|---:|---|---|')
  for (const item of report.checks || []) {
    const evidence = item.evidence?.length ? ` Evidence: ${item.evidence.map(value => markdownEvidence(value, evidenceHrefPrefix)).join('; ')}.` : ''
    lines.push(`| **${clean(item.status)}** | \`${clean(item.id)}\` | ${clean(item.dimensionName)} | ${item.points} | ${clean(item.level)} | ${clean(item.summary)}.${evidence} |`)
  }
}

function provenance(report) {
  return [
    ['Commit', report.commit || 'UNPROVEN'],
    ['Artifact', report.classification.artifact],
    ['Evaluated at', report.evaluatedAt],
    ['Artifact commit at', report.commitAt || 'UNPROVEN'],
    ['Identity', report.identity]
  ]
}

export function formatText(report) {
  const textKeys = { Commit: 'commit', Artifact: 'artifact', 'Evaluated at': 'evaluated-at', 'Artifact commit at': 'commit-at', Identity: 'identity' }
  const lines = [
    `# ${report.target}`,
    ...provenance(report).map(([key, value]) => `${textKeys[key]}: ${value}`),
    `classification: ${report.classification.types.join(', ')}`
  ]
  if (!report.classification.eligible) {
    lines.push('verdict: NOT_A_PLUGIN', `reason: ${report.classification.reason}`)
    return lines.join('\n')
  }
  lines.push(
    `quality: ${report.quality.confirmed}–${report.quality.upper}/100`,
    `coverage: ${report.quality.coverage}%`,
    `grade: ${report.quality.grade}`
  )
  if (report.adoption.stars !== null) lines.push(`adoption (not scored): ★ ${report.adoption.stars}, forks ${report.adoption.forks}`)
  lines.push('', '| Dimension | Confirmed | Possible | UNPROVEN |', '|---|---:|---:|---:|')
  for (const item of report.dimensions) lines.push(`| ${item.name} | ${item.confirmed} | ${item.possible} | ${item.unproven} |`)
  const gaps = prioritizedGaps(report)
  lines.push('', '## Highest-impact next actions')
  for (const item of gaps.slice(0, 5)) lines.push(`- ${item.status} ${item.id} (${item.points} points): ${item.summary}`)
  if (gaps.length > 5) lines.push(`- … ${gaps.length - 5} more; use --format markdown or --json for the complete evidence ledger.`)
  return lines.join('\n')
}

export function formatMarkdown(report, { evidenceHrefPrefix = null } = {}) {
  const lines = [
    '# DSH Plugin Quality Scorecard',
    '',
    `**Target:** ${clean(report.target)}`,
    '',
    '| Provenance | Value |',
    '|---|---|',
    ...provenance(report).map(([key, value]) => `| ${key} | ${clean(value)} |`),
    `| Classification | ${clean(report.classification.types.join(' + '))} |`,
    ''
  ]
  if (!report.classification.eligible) {
    lines.push('## NOT_A_PLUGIN', '', clean(report.classification.reason), '', '_No quality score was issued._')
    appendEvidenceLedger(lines, report, 'Inspection ledger (not scored)', evidenceHrefPrefix)
    lines.push('', '_Generated by dsh-plugin-bench._')
    return lines.join('\n')
  }
  lines.push(
    '## Result',
    '',
    `- **Quality interval:** ${report.quality.confirmed}–${report.quality.upper}/100`,
    `- **Evidence coverage:** ${report.quality.coverage}%`,
    `- **Grade:** ${clean(report.quality.grade)}`,
    `- **Adoption (not scored):** ${report.adoption.stars === null ? 'UNPROVEN' : `★ ${report.adoption.stars}, ${report.adoption.forks} forks`}`,
    '',
    '| Dimension | Confirmed | Possible | UNPROVEN |',
    '|---|---:|---:|---:|'
  )
  for (const item of report.dimensions) lines.push(`| ${clean(item.name)} | ${item.confirmed} | ${item.possible} | ${item.unproven} |`)
  const gaps = prioritizedGaps(report)
  lines.push('', '## Evidence gaps and failures', '')
  if (!gaps.length) lines.push('- None.')
  for (const item of gaps) {
    const evidence = item.evidence?.length ? ` Evidence: ${item.evidence.map(value => markdownEvidence(value, evidenceHrefPrefix)).join('; ')}.` : ''
    lines.push(`- **${item.status}** \`${item.id}\` (${item.points} points): ${clean(item.summary)}.${evidence}`)
  }
  appendEvidenceLedger(lines, report, 'Complete evidence ledger', evidenceHrefPrefix)
  lines.push('', '> A quality interval is not a popularity ranking. UNPROVEN increases only the upper bound; Stars and identity never change the quality score.', '', '_Generated by dsh-plugin-bench._')
  return lines.join('\n')
}

function badgeState(report) {
  if (!report.classification.eligible) return { value: 'not a plugin', color: '#6b7280' }
  if (report.quality.grade === 'UNSAFE') return { value: 'unsafe', color: '#b91c1c' }
  const value = `${report.quality.confirmed}–${report.quality.upper}`
  if (!report.quality.formal) return { value: `${value} provisional`, color: '#2563eb' }
  if (report.quality.confirmed >= 80) return { value, color: '#15803d' }
  if (report.quality.confirmed >= 70) return { value, color: '#4d7c0f' }
  if (report.quality.confirmed >= 60) return { value, color: '#a16207' }
  return { value, color: '#b91c1c' }
}

export function formatBadge(report) {
  const label = 'DSH quality'
  const state = badgeState(report)
  const left = 88
  const right = Math.max(88, 7 * state.value.length + 16)
  const width = left + right
  const title = `${label}: ${state.value}; ${report.target}; commit ${report.commit || 'UNPROVEN'}`
  return `<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${xml(title)}" width="${width}" height="20" viewBox="0 0 ${width} 20">
  <title>${xml(title)}</title>
  <linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#fff" stop-opacity=".16"/><stop offset="1" stop-opacity=".08"/></linearGradient>
  <clipPath id="r"><rect width="${width}" height="20" rx="3"/></clipPath>
  <g clip-path="url(#r)"><rect width="${left}" height="20" fill="#334155"/><rect x="${left}" width="${right}" height="20" fill="${state.color}"/><rect width="${width}" height="20" fill="url(#s)"/></g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11"><text x="${left / 2}" y="15" fill="#010101" fill-opacity=".3">${label}</text><text x="${left / 2}" y="14">${label}</text><text x="${left + right / 2}" y="15" fill="#010101" fill-opacity=".3">${xml(state.value)}</text><text x="${left + right / 2}" y="14">${xml(state.value)}</text></g>
</svg>`
}

export function renderReport(report, format = 'text', options = {}) {
  if (format === 'json') return JSON.stringify(report, null, 2)
  if (format === 'markdown') return formatMarkdown(report, options)
  if (format === 'badge') return formatBadge(report)
  if (format === 'text') return formatText(report)
  throw new Error(`unknown output format: ${format}`)
}
